import { Inter } from 'next/font/google'
import Header from '../components/header'
import Footer from '../components/footer'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Header /> {/* Include the Header here */}
      <main className={inter.className}>{children}
      </main>
      <Footer /> {/* Include the Footer here */}
    </html>
  )
}
